#!/usr/bin/env bash
# This script displays username, user id and home directory from /etc/passwd
while IFS=: read -r username _ uid _ _ home _
do
    echo "Username: $username"
    echo "User ID: $uid"
    echo "Home Directory: $home"
    echo "---"
done < /etc/passwd
