#!/usr/bin/env bash
# This script displays time from 1:01 to 12:59 with proper formatting
hour=1
while [ $hour -le 12 ]
do
    minute=1
    while [ $minute -le 59 ]
    do
        printf "%d:%02d\n" $hour $minute
        minute=$((minute + 1))
    done
    hour=$((hour + 1))
done
